"""Sprint 8 chunk 8.7 — Markdown gap report assembler."""

from __future__ import annotations

from datetime import UTC, datetime

from apps.api.services.gap_report import GapReportContext, render_gap_report


def _ctx(**overrides) -> GapReportContext:
    base = dict(
        run_id="11111111-1111-1111-1111-111111111111",
        user_id="user_test",
        summary="Top three concerns: stale RBAC, no signed commits, no MFA enforcement on org.",
        findings=[
            {
                "severity": "critical",
                "tsc_id": "CC6.1",
                "objection": "Org MFA not enforced for all members.",
                "recommended_next_step": "Toggle 'Require 2FA' in org security settings.",
            },
            {
                "severity": "low",
                "tsc_id": None,
                "objection": "Signed commits not required.",
                "recommended_next_step": "Enable 'Require signed commits' on the protected branch.",
            },
        ],
        scan_context={
            "control_map": [
                {
                    "control_id": "CC6.1",
                    "status": "failing",
                    "confidence": 0.92,
                    "rationale": "Org MFA disabled across the test fixture.",
                },
                {
                    "control_id": "CC6.6",
                    "status": "passing",
                    "confidence": 0.88,
                    "rationale": "Branch protection on main.",
                },
            ]
        },
        budget={"spent_usd": 0.014, "cap_usd": 0.5, "calls": 3},
        state="TASK_STATE_COMPLETED",
        generated_at=datetime(2026, 5, 8, 12, 0, 0, tzinfo=UTC),
    )
    base.update(overrides)
    return GapReportContext(**base)


def test_render_includes_summary_and_findings() -> None:
    body = render_gap_report(_ctx())
    assert "# Mock readiness challenge — draft gap report" in body
    assert "## Run summary" in body
    assert "## FAILING / partial controls" in body
    assert "CC6.1" in body
    assert "## Adversarial objections" in body
    assert "CRITICAL" in body
    assert "## Recommended next steps" in body
    assert "Toggle" in body
    # Footer present
    assert "Generated by AuditPilot" in body


def test_render_handles_empty_findings() -> None:
    body = render_gap_report(_ctx(findings=[]))
    assert "no objections" in body.lower()


def test_render_marks_budget_exceeded_state() -> None:
    body = render_gap_report(_ctx(state="TASK_STATE_BUDGET_EXCEEDED"))
    assert "Halted on budget cap" in body


def test_render_truncates_huge_failing_list() -> None:
    huge = [
        {"control_id": f"CC{i}", "status": "failing", "confidence": 0.5, "rationale": "x"}
        for i in range(50)
    ]
    body = render_gap_report(_ctx(scan_context={"control_map": huge}))
    assert "20 more failing/partial rows truncated" in body
